<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<div id="app">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>ค้นหาร้านอร่อย</h2>
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input name="keyword" type="text" class="form-control input-lg" placeholder="ex.bangsue" value='' v-model="input.keyword"/>
                        <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button" id="btn-restaurant-search" v-on:click="search">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                    </div>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 20px">
                <div class="list-group" v-for="_data in results">
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">{{_data.name}}</h4>
                        <p class="list-group-item-text">{{_data.address}}</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const vm = new Vue({
        el: '#app',
        data: {
            input: {
                keyword: null
            } ,
            results: []
        },
        mounted() {
            let keyword = $('input[name="keyword"]').val() || 'bangsue';
            this.find(keyword);
        },
        methods: {
            find(keyword) {
                axios.get(<?php echo '"' . $this->url('api-restaurants') . '"'; ?>+'?keyword=' + keyword)
                    .then(response => {
                        this.results = response.data.data
                    })
            },
            search(){
                this.find(this.input.keyword)
            }
        }
    });
</script>
